### ISSUE TITLE
Mod is incompatible with KubeJS 6.1

### ISSUE THREAD

**Issue by Saereth** [Bennyboy1695/MechanicalMachinery#1]
**Describe the bug**
KubeJS 6.1 introduced several breaking changes and the mod is no longer compatible. 

**Versions**
Forge Version: 43.2.21
Mod Version:  1.1.2

**To Reproduce**
1. Install kubejs latest version (6.1.x) and Mechanical Machinery + deps
2. Game will crash on load

**Additional context**
Latvian and Max have created an outreach room on the latvian discord to help addon mods directly make the transition to the new recipe schema system as outlined here, https://wiki.latvian.dev/books/kubejs/page/kubejs-61-update#bkmrk-for-addon-mod-develo
If you would be willing to update to use the new system they will work with you to help iron out any issues you run into. I appreciate the work you've put into this mod and I was looking at it as a replacement for create sifter in one of our upcoming packs.

**Comment by Bennyboy1695** [comment]
This has been fixed in [0b3b941](https://github.com/Bennyboy1695/MechanicalMachinery/commit/0b3b9415b0584789ff9d6fd04fede28556aedd60)
New versions has been uploaded to CurseForge and Modrinth.
Any other issues feel free to make another issue or ping me on discord (same username)
